about
InnaStarzhynska/team-project-icecream pull request #8
Opened 2022-12-15 20:43 UTC by 6teendollars

2022-12-15 21:13 UTC, 6teendollars commented
:)

2022-12-16 11:21 UTC, InnaStarzhynska requested changes
Привіт!
Треба деякі моменти доопрацювати:
1.  Зображення скачати звичайне та з підтримкою ретина екранів, прописані відповідні запити в html.  Назви мають бути зрозумілі і сформовані згідно домовленостей.
2.  SVG-іконка не потрібна, вона є у спрайті.
3. <h3 class="main-text-one">tradition and love </h3> - це не заголовок (див. ТЗ).
4.  Клас Container необхідно задати на div, яким огортаємо весь контент секції.
5.   <div class="button-flex"> - не може бути вкладений у button.
6.  ul[class],
ol[class] {
  list-style: none;
} видаляємо, це вже задано у базових стилях. 
7. Усі змінні шрифти задаємо через змінні.
8. Стилі необхідно прописати починаючи з мобайл версії.

2022-12-17 06:56 UTC, 6teendollars commented
по поводу ретины и всего что связано с изображением сделаю чуть позже, ну и модалку тоже

2022-12-17 07:32 UTC, InnaStarzhynska approved these changes

2022-12-17 07:33 UTC, merged